apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app : demo-app
    spec:
      containers:
        - name: demo-app
          image: krishnagopika4/brightspeed-demo:1.0.0
---

apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    service: demo-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer
